feat: add configurable bot accounts and gitlab license (#206)
## Description

Add ability to configure bot accounts when deploying gitlab. For each
account it will create the account in gitlab, create a pat for the
account, and store the pat in a secret. If using gitlab premium or
ultimate, it will create service accounts instead of regular user
accounts.

Also added the ability to set a gitlab license in the config chart since
that was needed for local testing on deploy. Tested that locally with a
trial license. Will add screenshot of that test result in comments.

## Related Issue

Fixes #205 
Fixes #207 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide
Steps](https://github.com/defenseunicorns/uds-package-gitlab/blob/main/CONTRIBUTING.md#developer-workflow)
followed

---------

Co-authored-by: Wayne Starr <Racer159@users.noreply.github.com>
Release-As: v17.2.7-uds.2

diff --git a/tasks/test.yaml b/tasks/test.yaml
--- a/tasks/test.yaml
+++ b/tasks/test.yaml
@@ -5,8 +5,9 @@ variables:
 tasks:
   - name: all
     actions:
-      - task: test:ingress
-      - task: test:ui
+      - task: ingress
+      - task: ui
+      - task: bot-account
 
   - name: ingress
     actions:
@@ -60,6 +61,23 @@ tasks:
       - cmd: rm -rf "${PROJECT_NAME}"
         dir: tests/data
 
+  - name: bot-account
+    description: Bot Account Access Tests
+    actions:
+      - cmd: kubectl get secret gitlab-test-bot -n test-bot -o jsonpath="{.data.TOKEN}" | base64 --decode
+        setVariables:
+          - name: GITLAB_TOKEN
+      - cmd: |
+          response=$(curl --write-out "%{http_code}" --silent --output /dev/null --header "PRIVATE-TOKEN: $GITLAB_TOKEN" https://gitlab.uds.dev/api/v4/user)
+
+          # Check if the status code is 200 (OK)
+          if [ "$response" -eq 200 ]; then
+            echo "GitLab API token is valid."
+          else
+            echo "Error: GitLab API token is invalid or cannot access the API."
+            exit 1
+          fi
+
   - name: create-doug-pat
     description: Create personal access token (PAT) for "doug" account
     actions:
@@ -77,3 +95,23 @@ tasks:
     actions:
       - description: Get the root password for GitLab (useful for local dev)
         cmd: ./uds zarf tools kubectl get secret -n gitlab gitlab-gitlab-initial-root-password -o jsonpath={.data.password} | base64 -d
+
+  # TODO (@ewyles) - might be useful in uds-common as a generic thing in the future
+  - name: bot-account-script
+    actions:
+      - description: Manually run the bot account script from the helm template locally
+        cmd: |
+          helm template charts/settings --show-only templates/bot-accounts-job.yaml | \
+          yq -r '.spec.template.spec.containers[0].args[0]' | \
+          sed 's|http://gitlab-webservice-default.gitlab.svc.cluster.local:8181|https://gitlab.uds.dev|g' | \
+          sh
+
+  - name: debug-bot-account-script
+    actions:
+      - description: Manually run the bot account script from the helm template locally
+        cmd: |
+          helm template charts/settings --show-only templates/bot-accounts-job.yaml | \
+          yq -r '.spec.template.spec.containers[0].args[0]' | \
+          sed 's|http://gitlab-webservice-default.gitlab.svc.cluster.local:8181|https://gitlab.uds.dev|g' | \
+          { echo "set -x"; cat; } | \
+          sh
