wait for instance to be ready before tests

diff --git a/tasks/test.yaml b/tasks/test.yaml
--- a/tasks/test.yaml
+++ b/tasks/test.yaml
@@ -76,12 +76,18 @@ tasks:
 
   - name: ingress
     actions:
-      - description: GitLab UI Health Check
-        wait:
-          network:
-            protocol: https
-            address: gitlab.uds.dev
-            code: 200
+      # `/-/readiness` endpoint returns 503 if any checks fail.
+      # When `?all=1` is specified, dependent services are also checked.
+      # https://docs.gitlab.com/ee/administration/monitoring/health_check.html#readiness
+      - description: GitLab Readiness Check
+        maxRetries: 30
+        cmd: |
+          STATUS=$(curl -s -o /dev/null --write-out '%{http_code}' 'https://gitlab.uds.dev/-/readiness?all=1')
+          echo "GitLab readiness status: ${STATUS}"
+          if [ $STATUS != "200" ]; then
+            sleep 10
+            exit 1
+          fi
 
   - name: git
     description: GitLab Repository Mirror Checks
